The great outdoors (#6)
Mojave-Sun/mojave-sun-13 pull request #1307
Opened 2021-10-30 06:34 UTC by AndrewL97

weather and sun and particool

2021-10-30 07:20 UTC, AndrewL97 commented
Lint issues regarding particle effects are lies 
fadein is a native byond var for /particles
and generators can be chained together

2021-11-03 05:18 UTC, Koshenko requested changes
Added a few small requests for changes.

2021-11-03 05:18 UTC, Koshenko commented on mojave/modules/outdoor_effects/code/modules/particool/particool.dm
> +		for(var/i = 1; i <= length(.); ++i)
Could probably optimize this slightly with `for(i in list)

2021-11-03 05:18 UTC, Koshenko commented on mojave/modules/outdoor_effects/code/_onclick/hud/fullscreen.dm
> +/atom/movable/screen/fullscreen/lighting_backdrop/Sunlight
Lowercase

2021-11-03 05:18 UTC, Koshenko commented on mojave/modules/outdoor_effects/code/controllers/subsystem/outdoor_effects.dm
> +/datum/time_of_day/Dawn
Lowercase all the datums in here

2021-11-03 05:18 UTC, Koshenko commented on mojave/modules/outdoor_effects/code/controllers/subsystem/particle_weather.dm
> +	qdel(runningWeather)
`QDELL_NULL()` is a nice shorthand macro for `qdel` then set the reference to null.

2021-11-06 03:42 UTC, merged