The Preferencing/TGUIening
Mojave-Sun/mojave-sun-13 pull request #1946
Opened 2021-12-23 01:13 UTC by TheRealScarHomie

## About The Pull Request

Makes the Pref menu like how it was AND improved! TGUI style and all that good stuff, also fixes the images on the Factions menu etc, ++ more stuff, TGUI is soul draining work so find out and see 👯.

![image](https://user-images.githubusercontent.com/63623569/147172770-463e6913-7460-4a3a-96cd-b1eeb41b08cd.png)

oooh image oooh, you like image

2021-12-23 06:19 UTC, Hekzder requested changes
This review is mostly just related to backpack stuff that I saw. Most of it is grammar or spelling related. Military is spelled with one L. 

The sack belt item thing is something I talked about with Original when it came to the gameplay concerns, but also like I mentioned in the comment about the sack, having a belt slot storage item as a choice on spawn interferes with a lot of roles starting equipment. In general it's not something we should really mess with right now, but we can maybe implement the sack as an item people can find in the world soon.

2021-12-23 06:19 UTC, Hekzder commented on mojave/code/modules/preferences/character.dm
> +#define MBACKPACK "Millitary Backpack"
```suggestion
#define MBACKPACK "Military Backpack"
```

2021-12-23 06:19 UTC, Hekzder commented on mojave/items/clothing/other/ms13backpacks.dm
> +	name = "millitary backpack"
```suggestion
	name = "military backpack"
```

2021-12-23 06:19 UTC, Hekzder commented on mojave/items/clothing/other/ms13backpacks.dm
> +/obj/item/storage/ms13/millitary
```suggestion
/obj/item/storage/ms13/military
```

2021-12-23 06:19 UTC, Hekzder commented on mojave/items/clothing/other/ms13backpacks.dm
> +	icon_state = "millitary"
```suggestion
	icon_state = "military"
```

2021-12-23 06:19 UTC, Hekzder commented on mojave/items/clothing/other/ms13backpacks.dm
> +	desc = "The roamers comapnion, a tall handcrafted pack, for storing all the essentials of wasteland livin'."
```suggestion
	desc = "The roamer's companion. A tall handcrafted pack for storing all the essentials of wasteland livin'."
```

2021-12-23 06:19 UTC, Hekzder commented on mojave/code/modules/preferences/character.dm
> +#define SACK "Sack"
The storage sack, and generally having a belt slot storage item on spawn is not really something we're wanting to do right now. The item itself is fine to stay in but shouldn't be given to anyone on spawn for a variety of reasons, chiefly that it interferes with starting equipment for **a lot** of roles. But also that it has some _storage balance concerns_ that go against **THE VISION**

2021-12-23 13:49 UTC, TheRealScarHomie commented
ok all done

2021-12-23 16:34 UTC, TheRealScarHomie commented
ok all done

2021-12-23 21:04 UTC, Hekzder requested changes
Travelpack is missing an inventory state, currently the inventory.dmi icon it has is identical to the world state. 

When choosing the military backpack in character setup, the icon shows a sack instead. 

The NCR do not get their faction specific backpacks and instead get the chosen backpack in character setup. Faction backpack choice may remedy this if you can get it set up? I imagine in the future we'll have more faction specific backpacks like a Vault-Tec satchel, BoS backpack, etc.

2021-12-23 21:04 UTC, Hekzder commented
I also just pushed a commit that fixes the misspelled military backpack inventory state, fixes a couple missing parent proc calls, and should fix the integration test fails on the backpack thing.

2021-12-31 22:47 UTC, TheRealScarHomie commented
ok I would actually consider this finished now

2022-01-03 07:20 UTC, Hekzder approved these changes
Aside from a runtime that we will try to look into when possible, this seems good for a merge but @Koshenko will probably be the one to pull the trigger after he takes a look.

2022-01-05 01:39 UTC, merged