Hairenining minor
Mojave-Sun/mojave-sun-13 pull request #242
Opened 2021-08-17 01:37 UTC by ProfessorPopoff

This PR starts to unscuff hair when worn with a hat. I've painstakingly gone through each hair sprite and fitted it to the average hat. Everything should be good. Putting this up as a draft for now.

2021-08-17 01:54 UTC, TheRealScarHomie commented on code/modules/mob/living/carbon/human/species.dm
> +				//MOJAVE EDIT BEGIN
double begin :trollface:

2021-08-17 03:30 UTC, Hekzder requested changes
Double `MOJAVE EDIT BEGIN` like Scar said.

2021-08-17 03:30 UTC, Hekzder commented on code/modules/mob/living/carbon/human/species.dm
> +				//MOJAVE EDIT BEGIN
```suggestion
				//MOJAVE EDIT END
```

2021-08-17 03:30 UTC, Hekzder commented on code/modules/mob/living/carbon/human/species.dm
> +				//MOJAVE EDIT BEGIN
```suggestion
				//MOJAVE EDIT END
```

2021-08-17 16:59 UTC, ProfessorPopoff commented
> Double `MOJAVE EDIT BEGIN` like Scar said.

It's a feature.

2021-08-17 18:50 UTC, ProfessorPopoff commented
There might be a few minor hiccups here and there, but overall every hair i've tested is pretty nice looking, now. 
![e0052c5af46940a77f7f6b7b5eed3108](https://user-images.githubusercontent.com/51188571/129783563-93ee686b-3ed3-4839-a73b-18ab6c15477b.gif)
![bbe9131fc3b0b31b6fe63c8a3b1a4c30](https://user-images.githubusercontent.com/51188571/129783565-507158b6-4543-463c-91c0-e34baa98f568.gif)
![2e67fa4547ae873752c199625db7a145](https://user-images.githubusercontent.com/51188571/129783569-83386913-6e7d-43db-bad5-80e538fe4e4d.gif)
![03a13467f697f0e8d07b4f2b39af81f4](https://user-images.githubusercontent.com/51188571/129783573-b7bda6b9-2deb-4277-b2dd-b8902c3338df.gif)

Ever hair will now not clip through the top of helmets/hat 100% guarantee, if not- your money back. They look pretty cool, now. Drip is at an all-time high. Opening this up, now.

2021-08-18 04:01 UTC, Hekzder approved these changes
Looks pretty good, tested it a bit and it seems to work decently well. I don't imagine this is 100% completely and utterly bug free but I wouldn't expect _every_ single headgear to have been tested on _every_ single hair style. 

Any potential related bugs are really tiny and we can squash them as they arise. Ultimately this is pretty epic. Massive drip buff.

2021-08-18 05:18 UTC, merged