Ammoening part 1
Mojave-Sun/mojave-sun-13 pull request #268
Opened 2021-08-19 07:58 UTC by ProfessorPopoff

Adds in a bunch of prettier sprites by Infra for our ammo and enables the inventory icon element on them all. 

![image](https://user-images.githubusercontent.com/51188571/130030568-9d3a3acd-b2b1-44a9-8ffd-3bd4a2b7f152.png)

They look great, good job Infra. Now for the rest of them... Later. It'll do for now. I cleaned up wherever I could while in the process. I apologize as I don't have the heart in me tonight to shrink all the big ones left over down to world states, but I might tomorrow. Leaving this up for the mean time.

2021-08-19 15:09 UTC, Hekzder requested changes

2021-08-19 15:09 UTC, Hekzder commented on mojave/effects/spawners/lootdrop/gunloot.dm
> -				""
Keep the quotes, this applies to the entire file. The gun loot spawner checks for three items, the extra empty spots are filled in by the quotes to minimize potential issues.

2021-08-19 15:53 UTC, Hekzder requested changes

2021-08-19 15:53 UTC, Hekzder commented on mojave/items/guns/weapons/energy/energy_pistol.dm
> +	cell_type = /obj/item/stock_parts/cell/ms13/mfc
You'll need to make a new ammo_type for the adv. las pistol that has proper energy usage to put it at 20 shots with the amount of energy that the MFC has. Laser pistols are balanced around/intended to have 20 shots.

2021-08-19 16:54 UTC, ProfessorPopoff commented
Check and check.

2021-08-19 19:35 UTC, Hekzder requested changes
Make the Laser Defender a child of Advanced Las Pistol since I just realized it also uses MFC. You shouldn't have to do anything aside from just make it a child of Advanced. Then this is good to merge if you aren't doing any other work on it.

2021-08-20 23:15 UTC, Hekzder approved these changes
This should be good from what I can see.

2021-08-20 23:26 UTC, merged