Fishing Draft PR
Mojave-Sun/mojave-sun-13 pull request #353
Opened 2021-08-26 03:29 UTC by Technobug14

## About The Pull Request
Just a draft. Fishing soon. Highly WIP, old code being fixed up

## Why It's Good For The Game
Fishing

## Changelog
:cl:
fishing
/:cl:

2021-09-13 00:28 UTC, mrpibb4201337 commented
Owned

2021-10-01 04:29 UTC, AndrewL97 requested changes

2021-10-01 04:29 UTC, AndrewL97 commented on mojave/fishing/fishing.dm
> +			getFished()
Missing indent after `if(do_after...`

2021-12-22 01:04 UTC, Hekzder commented
Closing as #1922 was merged.

2021-12-22 01:04 UTC, closed without merging